### ISSUE TITLE
show-list error

### ISSUE THREAD

**Issue by malmstroem** [mheap/trello-cli#19]
Trying out this tool as it seems very useful. Is it possible to print out which list each card belongs to when using the assigned-to-me command? Can I sort them according to, for example, due date?

I also get an error when I'm trying using the show-list option:

bin/trello show-list -b private -l doing

TypeError: object is not a function
    at /tmp/tc/trello-cli/src/node-trello-wrapper.js:37:17
    at Request._callback (/tmp/tc/trello-cli/node_modules/node-trello/lib/node-trello.coffee:60:16)
    at Request.self.callback (/tmp/tc/trello-cli/node_modules/node-trello/node_modules/request/main.js:122:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/tmp/tc/trello-cli/node_modules/node-trello/node_modules/request/main.js:661:16)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/tmp/tc/trello-cli/node_modules/node-trello/node_modules/request/main.js:623:14)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by ksk100** [comment]
Hi, thanks for bug report.  I've fixed that issue and will submit a PR.

**Comment by ksk100** [comment]
As the for the feature requests; shouldn't be too much of a big job.

I might be able to get round to it this week, but do feel free to go ahead and submit something if you want, I'm sure @mheap would be appreciative.

**Comment by mheap** [comment]
I've just merged https://github.com/mheap/trello-cli/pull/20 which should fix the issue, thanks for the fix @ksk100.

As for the sorting feature request, please do submit a PR :)

**Comment by malmstroem** [comment]
thanks for the quick fix, everything is working as expected now!
