### ISSUE TITLE
Source tarball for packaging

### ISSUE THREAD

**Issue by Tonus1** [mheap/trello-cli#201]
Hi
I am maintaining the script to package trello-cli for Slackware and noticed it has drasticly changed and do not permit an offline install anymore AFAIK.

Do you think it could be possible to release a tarball as previously crafted ?

Regards

**Comment by Tonus1** [comment]
Perhaps is it I messed with directories.
It's all about
```
DESTDIR=$PKG npm install -g $CWD/$PRGNAM\@$VERSION.tar.gz
```

**Comment by mheap** [comment]
That _should_ work. The new version works with an [Arch PKGBUILD ](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=trello-cli)

**Comment by mheap** [comment]
@Tonus1 Did you get it working?

**Comment by Tonus1** [comment]
I believe it's a problem in how the source is crafted. I tryed after downlowding from here
```
npm install -g trello-cli@1.0.5.tar.gz
```

Got that
```
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.2.3
2 info using node@v20.10.0
3 timing npm:load:whichnode Completed in 9ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/usr/lib64/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 9ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:setEnvs Completed in 1ms
15 timing config:load Completed in 23ms
16 timing npm:load:configload Completed in 24ms
17 timing config:load:flatten Completed in 5ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install trello-cli@1.0.5.tar.gz
21 verbose argv "install" "--global" "trello-cli@1.0.5.tar.gz"
22 timing npm:load:setTitle Completed in 1ms
23 timing npm:load:display Completed in 1ms
24 verbose logfile logs-max:10 dir:/root/.npm/_logs/2023-12-16T21_58_17_721Z-
25 verbose logfile /root/.npm/_logs/2023-12-16T21_58_17_721Z-debug-0.log
26 timing npm:load:logFile Completed in 13ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 1ms
29 timing npm:load Completed in 75ms
30 timing config:load:flatten Completed in 1ms
31 timing arborist:ctor Completed in 2ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 11ms
35 timing idealTree:userRequests Completed in 5ms
36 silly idealTree buildDeps
37 silly fetch manifest trello-cli@file:../../mnt/hd/Sandbox/Slackbuilds.org/office/trello-cli/1.0.5.tar.gz
38 warn tarball tarball data for trello-cli@file:../../mnt/hd/Sandbox/Slackbuilds.org/office/trello-cli/1.0.5.
tar.gz (null) seems to be corrupted. Trying again.
39 warn tarball tarball data for trello-cli@file:../../mnt/hd/Sandbox/Slackbuilds.org/office/trello-cli/1.0.5.
tar.gz (null) seems to be corrupted. Trying again.
40 silly placeDep ROOT trello-cli@ OK for:  want: file:../../mnt/hd/Sandbox/Slackbuilds.org/office/trello-cli/
1.0.5.tar.gz
41 timing idealTree:#root Completed in 71ms
42 timing idealTree:node_modules/trello-cli Completed in 0ms
43 timing idealTree:buildDeps Completed in 76ms
44 timing idealTree:fixDepFlags Completed in 2ms
45 timing idealTree Completed in 96ms
46 timing command:install Completed in 138ms
47 verbose stack Error: ENOENT: no such file or directory, open '/mnt/hd/Sandbox/Slackbuilds.org/office/trello
-cli/1.0.5.tar.gz'
48 verbose cwd /mnt/hd/Sandbox/Slackbuilds.org/office/trello-cli
49 verbose Linux 5.15.139
50 verbose node v20.10.0
51 verbose npm  v10.2.3
52 error code ENOENT
53 error syscall open
54 error path /mnt/hd/Sandbox/Slackbuilds.org/office/trello-cli/1.0.5.tar.gz
55 error errno -2
56 error enoent ENOENT: no such file or directory, open '/mnt/hd/Sandbox/Slackbuilds.org/office/trello-cli/1.0
.5.tar.gz'
57 error enoent This is related to npm not being able to find a file.
57 error enoent
58 verbose exit -2
59 timing npm Completed in 503ms
60 verbose unfinished npm timer reify 1702763898027
61 verbose unfinished npm timer reify:loadTrees 1702763898059
62 verbose code -2
63 error A complete log of this run can be found in: /root/.npm/_logs/2023-12-16T21_58_17_721Z-debug-0.log
```

I did try with the .tgz archive linked in ARCH build with no joy.

Next tryed without the @ replaced with dash 
```
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.2.3
2 info using node@v20.10.0
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib64/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 4ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:setEnvs Completed in 1ms
15 timing config:load Completed in 13ms
16 timing npm:load:configload Completed in 13ms
17 timing config:load:flatten Completed in 6ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install trello-cli-1.0.5.tar.gz
21 verbose argv "install" "--global" "trello-cli-1.0.5.tar.gz"
22 timing npm:load:setTitle Completed in 2ms
23 timing npm:load:display Completed in 1ms
24 verbose logfile logs-max:10 dir:/root/.npm/_logs/2023-12-16T22_09_21_448Z-
25 verbose logfile /root/.npm/_logs/2023-12-16T22_09_21_448Z-debug-0.log
26 timing npm:load:logFile Completed in 14ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 61ms
30 timing config:load:flatten Completed in 1ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 5 files
33 timing idealTree:init Completed in 11ms
34 silly logfile done cleaning log files
35 timing idealTree:userRequests Completed in 145ms
36 silly idealTree buildDeps
37 silly fetch manifest trello-cli@file:../../mnt/hd/Sandbox/Slackbuilds.org/office/trello-cli/trello-cli-1.0.
5.tar.gz
38 silly placeDep ROOT trello-cli@ OK for:  want: file:../../mnt/hd/Sandbox/Slackbuilds.org/office/trello-cli/
trello-cli-1.0.5.tar.gz
39 timing idealTree:#root Completed in 129ms
40 timing idealTree:node_modules/trello-cli Completed in 0ms
41 timing idealTree:buildDeps Completed in 131ms
42 timing idealTree:fixDepFlags Completed in 1ms
43 timing idealTree Completed in 290ms
44 timing reify:loadTrees Completed in 296ms
45 timing reify:diffTrees Completed in 2ms
46 silly reify moves {}
47 timing reify:retireShallow Completed in 1ms
48 timing reify:createSparse Completed in 1ms
49 timing reify:loadBundles Completed in 0ms
50 timing reifyNode:node_modules/trello-cli Completed in 56ms
51 timing reify:unpack Completed in 56ms
52 timing reify:unretire Completed in 0ms
53 timing build:queue Completed in 1ms
54 timing build:deps Completed in 1ms
55 timing build Completed in 2ms
56 timing reify:build Completed in 2ms
57 timing reify:trash Completed in 0ms
58 timing reify Completed in 394ms
59 silly ADD node_modules/trello-cli
60 timing command:install Completed in 408ms
61 verbose exit 0
62 timing npm Completed in 698ms
63 info ok
```

**Comment by Tonus1** [comment]
Tryed to mess around and while trying to deal with only the `trello-cli-trello-cli/packages/trello-cli` directory I get the following error :
```
39 silly fetch manifest @oclif/core@^1.19.1
40 silly fetch manifest @oclif/plugin-autocomplete@^1.3.6
41 silly fetch manifest @oclif/plugin-help@^5
42 silly fetch manifest @oclif/plugin-plugins@^2.1.4
43 timing idealTree Completed in 111ms
44 timing command:install Completed in 126ms
45 verbose stack Error: Unsupported URL Type "workspace:": workspace:*
45 verbose stack     at unsupportedURLType (/usr/lib64/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:310:15)
45 verbose stack     at fromURL (/usr/lib64/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:367:13)
45 verbose stack     at Function.resolve (/usr/lib64/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:83:12)
45 verbose stack     at visit (/usr/lib64/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1020:39)
45 verbose stack     at visitNode (/usr/lib64/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:58:25)
45 verbose stack     at next (/usr/lib64/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:44:19)
45 verbose stack     at depth (/usr/lib64/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:83:10)
45 verbose stack     at depth (/usr/lib64/node_modules/npm/node_modules/treeverse/lib/depth.js:27:12)
45 verbose stack     at #buildDepStep (/usr/lib64/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:949:7)
45 verbose stack     at async Arborist.buildIdealTree (/usr/lib64/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
46 verbose cwd /tmp/SBo/trello-cli
47 verbose Linux 5.15.145
48 verbose node v20.10.0
49 verbose npm  v10.2.3
50 error code EUNSUPPORTEDPROTOCOL
51 error Unsupported URL Type "workspace:": workspace:*
52 verbose exit 1
53 timing npm Completed in 315ms
54 verbose unfinished npm timer reify 1704450323087
55 verbose unfinished npm timer reify:loadTrees 1704450323096
56 verbose unfinished npm timer idealTree:buildDeps 1704450323172
57 verbose unfinished npm timer idealTree:#root 1704450323173
58 verbose code 1
```
Does it shed some light on what I miss ?

Regards

**Comment by mheap** [comment]
It does! It seems as though you're trying to package from the repo rather than the built CLI. This will not work from the latest changes.

Try downloading the `.tar.gz` like the `PKGBUILD` does and untar it. Then use the folder there as the source for your packaging

**Comment by Tonus1** [comment]
Yes ! Thank you !
That seem to work : I have the new version running :) 

Is it normal I lost the auth I had previously ? I just want to warn SlackBuild's users they will have to get re-authentified even if it was previously installed and running.

**Comment by Tonus1** [comment]
I tried to sync the cache and got en error
```
┗━────◉ trello sync

/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:24
        return this.db.prepare(sql).run(...args);
                                    ^
SqliteError: NOT NULL constraint failed: boards.orgId
    at DB.run (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:24:37)
    at DB.upsert (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:32:21)
    at default_1.processBoard (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:70:17)
    at default_1.process (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:53:18)
    at default_1.run (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:49:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SyncIndex.run (/usr/lib64/node_modules/trello-cli/dist/commands/sync/index.js:7:9)
    at async SyncIndex._run (/usr/lib64/node_modules/trello-cli/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/lib64/node_modules/trello-cli/node_modules/@oclif/core/lib/config/config.js:301:25) {
  code: 'SQLITE_CONSTRAINT_NOTNULL'
}

Node.js v20.10.0
```

Do you think it's related to my package or shall I open a new issue ?

Regards

**Comment by mheap** [comment]
That's strange. It's as though the data returned by the API is incomplete. Can you paste the exact commands from install to sync that you run?

**Comment by flowrange** [comment]
I just got a similar error. I installed it on Arch from the AUR, added API Key & auth token, and ran `trello sync` without doing anything else. 

```
> trello sync

/usr/lib/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:24
        return this.db.prepare(sql).run(...args);
                                    ^
SqliteError: NOT NULL constraint failed: orgs.creatorId
    at DB.run (/usr/lib/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:24:37)
    at DB.upsert (/usr/lib/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:32:21)
    at default_1.processOrg (/usr/lib/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:62:17)
    at default_1.process (/usr/lib/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:57:18)
    at default_1.run (/usr/lib/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:49:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SyncIndex.run (/usr/lib/node_modules/trello-cli/dist/commands/sync/index.js:7:9)
    at async SyncIndex._run (/usr/lib/node_modules/trello-cli/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/lib/node_modules/trello-cli/node_modules/@oclif/core/lib/config/config.js:301:25) {
  code: 'SQLITE_CONSTRAINT_NOTNULL'
}

Node.js v18.9.0
```

The only difference is that the `ords.creatorId` fails the constraint instead of `boards.orgId`. Some fields may be unexpectedly returned as NULL ?

**Comment by mheap** [comment]
@Tonus1 Yes, you will need to re-auth unfortunately due to the new profile support.

@Tonus1 @flowrange Let's follow up in #202
