### ISSUE TITLE
trello sync - Null constraint error

### ISSUE THREAD

**Issue by mheap** [mheap/trello-cli#202]
I tried to sync the cache and got en error
```
┗━────◉ trello sync

/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:24
        return this.db.prepare(sql).run(...args);
                                    ^
SqliteError: NOT NULL constraint failed: boards.orgId
    at DB.run (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:24:37)
    at DB.upsert (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:32:21)
    at default_1.processBoard (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:70:17)
    at default_1.process (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:53:18)
    at default_1.run (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:49:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SyncIndex.run (/usr/lib64/node_modules/trello-cli/dist/commands/sync/index.js:7:9)
    at async SyncIndex._run (/usr/lib64/node_modules/trello-cli/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/lib64/node_modules/trello-cli/node_modules/@oclif/core/lib/config/config.js:301:25) {
  code: 'SQLITE_CONSTRAINT_NOTNULL'
}

Node.js v20.10.0
```

Do you think it's related to my package or shall I open a new issue ?

Regards

_Originally posted by @Tonus1 in https://github.com/mheap/trello-cli/issues/201#issuecomment-1878798387_

**Comment by mheap** [comment]
Related: https://github.com/mheap/trello-cli/issues/201#issuecomment-1887282579

From @flowrange

I just got a similar error. I installed it on Arch from the AUR, added API Key & auth token, and ran `trello sync` without doing anything else. 

```
> trello sync

/usr/lib/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:24
        return this.db.prepare(sql).run(...args);
                                    ^
SqliteError: NOT NULL constraint failed: orgs.creatorId
    at DB.run (/usr/lib/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:24:37)
    at DB.upsert (/usr/lib/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:32:21)
    at default_1.processOrg (/usr/lib/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:62:17)
    at default_1.process (/usr/lib/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:57:18)
    at default_1.run (/usr/lib/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:49:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SyncIndex.run (/usr/lib/node_modules/trello-cli/dist/commands/sync/index.js:7:9)
    at async SyncIndex._run (/usr/lib/node_modules/trello-cli/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/lib/node_modules/trello-cli/node_modules/@oclif/core/lib/config/config.js:301:25) {
  code: 'SQLITE_CONSTRAINT_NOTNULL'
}

Node.js v18.9.0
```

The only difference is that the `ords.creatorId` fails the constraint instead of `boards.orgId`. Some fields may be unexpectedly returned as NULL ?

**Comment by mheap** [comment]
I've tried to reproduce but can't.

```
❯ trello --version
trello-cli/1.0.5 darwin-arm64 node-v18.12.1
```

I deleted my `~/.trello-cli` folder and re-authed with the following commands:

```
trello auth:api-key KEY_HERE
trello auth:token MY_TOKEN
trello sync
```

The process completed successfully. 

@Tonus1 @flowrange Could you provide the output of `trello --version`? How comfortable are you hacking around in the CLI files to add debugging lines?

**Comment by mheap** [comment]
I've just downloaded the archive used in the `PKGBUILD` and ran `npm install && ./bin/run sync` which also completed successfully

**Comment by Tonus1** [comment]
So just moved old config file (btw would be nice to comply to $XDG_CONFIG_DIR) and ran the process to authenticate.
Got the following error despite the commands seem to work (I can list several boards/lists/cards) 
``/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:24
        return this.db.prepare(sql).run(...args);
                                    ^
SqliteError: NOT NULL constraint failed: boards.orgId
    at DB.run (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:24:37)
    at DB.upsert (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/db.js:32:21)
    at default_1.processBoard (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:70:17)
    at default_1.process (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:53:18)
    at default_1.run (/usr/lib64/node_modules/trello-cli/node_modules/@trello-cli/cache/dist/sync.js:49:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SyncIndex.run (/usr/lib64/node_modules/trello-cli/dist/commands/sync/index.js:7:9)
    at async SyncIndex._run (/usr/lib64/node_modules/trello-cli/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/lib64/node_modules/trello-cli/node_modules/@oclif/core/lib/config/config.js:301:25) {
  code: 'SQLITE_CONSTRAINT_NOTNULL'
}

Node.js v20.10.0
```

My build script is as follow
```
cd $(dirname $0) ; CWD=$(pwd)
  │ 
  │ PRGNAM=trello-cli
  │ VERSION=${VERSION:-1.0.5}
  │ BUILD=${BUILD:-1}
  │ TAG=${TAG:-_SBo}
  │ PKGTYPE=${PKGTYPE:-tgz}
  │ 
  │ if [ -z "$ARCH" ]; then
  │   case "$( uname -m )" in
  │     i?86) ARCH=i586 ;;
  │     arm*) ARCH=arm ;;
  │        *) ARCH=$( uname -m ) ;;
  │   esac
  │ fi
  │ 
  │ # If the variable PRINT_PACKAGE_NAME is set, then this s
  │ cript will report what
  │ # the name of the created package would be, and then exi
  │ t. This information
  │ # could be useful to other scripts.
  │ if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  │   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  │   exit 0
  │ fi
  │ 
  │ TMP=${TMP:-/tmp/SBo}
  │ PKG=$TMP/package-$PRGNAM
  │ OUTPUT=${OUTPUT:-/tmp}
  │ 
  │ set -e
  │ 
  │ rm -rf $PKG
  │ mkdir -p $TMP $PKG $OUTPUT
  │ cd $TMP
  │ rm -rf $PRGNAM-$VERSION
  │ tar xvf $CWD/$PRGNAM-$VERSION.tgz
  │ cd package
  │ chown -R root:root .
  │ find -L . \
  │  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o 
  │ -perm 555 \
  │   -o -perm 511 \) -exec chmod 755 {} \; -o \
  │  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o 
  │ -perm 444 \
  │   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
  │ 
  │ DESTDIR=$PKG npm install -g $CWD/$PRGNAM-$VERSION.tgz
  │ 
  │ mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
  │ cp -a \
  │   README.md \
  │   $PKG/usr/doc/$PRGNAM-$VERSION
  │ cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERS
  │ ION/$PRGNAM.SlackBuild
  │ 
  │ mkdir -p $PKG/install
  │ cat $CWD/slack-desc > $PKG/install/slack-desc
  │ 
  │ cd $PKG
  │ /sbin/makepkg -l n -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$
  │ BUILD$TAG.$PKGTYPE
```

With this links
```
PRGNAM="trello-cli"
  │ VERSION="1.0.5"
  │ HOMEPAGE="https://github.com/mheap/trello-cli/"
  │ DOWNLOAD="https://registry.npmjs.org/trello-cli/-/trello
  │ -cli-1.0.5.tgz"
  │ MD5SUM="5cc7e773c26baa9809c3a2e5acb9f2bd"
  │ DOWNLOAD_x86_64=""
  │ MD5SUM_x86_64=""
  │ REQUIRES="google-go-lang nodejs"
```

**Comment by Tonus1** [comment]
> @Tonus1 @flowrange Could you provide the output of `trello --version`? How comfortable are you hacking around in the CLI files to add debugging lines?

I'm willing to help debug. I can edit/test but have very limited knowledge. 

```
trello --version
trello-cli/1.0.5 linux-x64 node-v20.10.0
```

**Comment by mheap** [comment]
Ok, I've confirmed that it's not the node version:

```
❯ trello --version
trello-cli/1.0.5 darwin-arm64 node-v20.10.0
```

And it's not the OS:

```
michael@ubuntu$ trello --version
trello-cli/1.0.5 linux-x64 node-v18.13.0
```

It must be something specific to your account. Let me add some additional debugging and see if I can submit a release with debug logs

**Comment by mheap** [comment]
`trello-cli@1.0.6` is now published. If sync errors, it will now log the board that caused the error. Please redact any sensitive information then post the dumped JSON in this issue.

**Comment by flowrange** [comment]
Thanks for the quick response !

Here's the relevant part of the JSON :

```Error processing board {
  id: '<some board id>',
  name: '<some board name>',
  idOrganization: '<some org id>',
  [...]
  organization: {
    id: '<some org id>',
    displayName: '<some org name>',
    idMemberCreator: null
  }
}```

As you can see, there's no creator id for the organization. It was created by a former colleague, who left our company. We removed his account from the organization, giving a null creator.

**Comment by mheap** [comment]
Aha! That would do it. All of the fields are populated for me (solo user of Trello), so I opted to make the fields non-null. Let me think about the best way to resolve this

**Comment by Tonus1** [comment]
Got quite same thing !
First it was about boards that were close and that I just deleted.
Then this 
```
Error processing board {
  id: 'something',
  name: 'Planning',
  closed: false,
  idOrganization: 'somthingelse',
  pinned: false,
  starred: false,
  url: 'https://trello.com/b/XXXXXXXX/planning',
  shortLink: 'XXXXXXXXX',
  idMemberCreator: null,
  cards: [
    {
      id: 'XXXXX',
      closed: true,
      idBoard: 'smoething',
      idList: 'YYYYYYYYYYY',
      name: "Bla blah blah.",
      shortLink: 'ZZZZZZZZZ'
    },
[......................................................]
 ],
  organization: {
    id: 'something',
    displayName: 'NAME',
    idMemberCreator: 'AAAAAAAAAAAAAAAAAAAAAAAA'
  }
}
    SqliteError: NOT NULL constraint failed: boards.creatorId
    Code: SQLITE_CONSTRAINT_NOTNULL
```

**Comment by Tonus1** [comment]
Hi
Came accross this one
```
    SqliteError: NOT NULL constraint failed: labels.color
    Code: SQLITE_CONSTRAINT_NOTNULL
```

**Comment by mheap** [comment]
I've just pushed 1.0.7 which should resolve this. Thank you for the patience
