### ISSUE TITLE
log is not defined

### ISSUE THREAD

**Issue by helsont** [mheap/trello-cli#21]
Just install the module globally and set the authentication. Then this happened

```
trello add-card -b Personal -l Habits "Fix Bed"                                                                                                             ] 8:32 AM
/Users/winter/.nvm/versions/node/v4.2.4/lib/node_modules/trello-cli/src/commands/add-card.js:27
                log.error("Unknown error:");
                ^

ReferenceError: log is not defined
    at Object.trelloApiCommand.makeTrelloApiCall (/Users/winter/.nvm/versions/node/v4.2.4/lib/node_modules/trello-cli/src/commands/add-card.js:27:17)
    at Object.cb (/Users/winter/.nvm/versions/node/v4.2.4/lib/node_modules/trello-cli/src/commands/add-card.js:142:38)
    at Object.ArgParser.parse (/Users/winter/.nvm/versions/node/v4.2.4/lib/node_modules/trello-cli/node_modules/nomnom/nomnom.js:302:15)
    at Object.<anonymous> (/Users/winter/.nvm/versions/node/v4.2.4/lib/node_modules/trello-cli/bin/trello:74:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
```

**Comment by ksk100** [comment]
Yep, my bad.  There's a typo there, I'll fix it now.
