### ISSUE TITLE
Cannot read property 'toLowerCase()' of Null

### ISSUE THREAD

**Issue by durmiun** [mheap/trello-cli#26]
I get the below error message whenever I try running any commands with the trello-cli.

I'll be happy to provide further details if you can tell me what you need.

```
λ trello add-card "test" "this is a description" -b "Spells" -l "Spells Known"
error: Unknown error:
C:\users\me\node_modules\trello-cli\src\commands\add-card.js:28
                throw err;
                ^

TypeError: Cannot read property 'toLowerCase' of null
    at Translator.getBoardIdByName (C:\users\me\node_modules\trello-cli\src\translator.js:78:21)
    at Object.trelloApiCommand.makeTrelloApiCall (C:\users\me\node_modules\trello-cli\src\commands\add-card.js:14:34)
    at Object.cb (C:\users\me\node_modules\trello-cli\src\commands\add-card.js:142:38)
    at Object.ArgParser.parse (C:\users\me\node_modules\nomnom\nomnom.js:302:15)
    at Object.<anonymous> (C:\users\me\node_modules\trello-cli\bin\trello:74:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
```

**Comment by ksk100** [comment]
Hi,

Does this error happen on every single command?  I can't reproduce it as
yet.  If you could post the message from another card, that would allow us
to see the line number where the error occurs in a different file.

Thanks

2016-04-16 5:11 GMT+01:00 durmiun <notifications@github.com>:

**Comment by durmiun** [comment]
Sure!  I think it happened on all commands that I tried.  Let me run through them and post results...

"assigned-to-me"
```
C:\users\jason\downloads
λ trello assigned-to-me
C:\users\jason\node_modules\trello-cli\src\commands\assigned-to-me.js:19
        cards[item.idBoard].push(item.name.replace(/\n/g, ""));
                                          ^

TypeError: Cannot read property 'replace' of undefined
    at C:\users\jason\node_modules\trello-cli\src\commands\assigned-to-me.js:19:43
    at Request._callback (C:\users\jason\node_modules\node-trello\lib\node-trello.coffee:60:16)
    at Request.self.callback (C:\users\jason\node_modules\request\main.js:122:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (C:\users\jason\node_modules\request\main.js:661:16)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (C:\users\jason\node_modules\request\main.js:623:14)
    at emitNone (events.js:85:20)
```

"Show-list"
```
λ trello show-list -b "spells master list" -l "Spells known"
C:\users\jason\node_modules\trello-cli\src\translator.js:78
    if (boards[i][1].toLowerCase() == name){
                    ^

TypeError: Cannot read property 'toLowerCase' of null
    at Translator.getBoardIdByName (C:\users\jason\node_modules\trello-cli\src\translator.js:78:21)
    at Object.cb (C:\users\jason\node_modules\trello-cli\src\commands\show-list.js:27:30)
    at Object.ArgParser.parse (C:\users\jason\node_modules\nomnom\nomnom.js:302:15)
    at Object.<anonymous> (C:\users\jason\node_modules\trello-cli\bin\trello:74:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
```

"Add-board" this one appears interesting... It doesn't give me an error message, but it doesn't add a board, either.

```
λ trello add-board -b "test" -d "test board"
Organisation, board and list cache refreshed
```

"add-list"
```
λ trello add-list -b "bills" -l "test list"
error: Unknown error:
C:\users\jason\node_modules\trello-cli\src\commands\add-list.js:29
                throw err;
                ^

TypeError: Cannot read property 'toLowerCase' of null
    at Translator.getBoardIdByName (C:\users\jason\node_modules\trello-cli\src\translator.js:78:21)
    at Object.trelloApiCommand.makeTrelloApiCall (C:\users\jason\node_modules\trello-cli\src\commands\add-list.js:15:34)
    at Object.cb (C:\users\jason\node_modules\trello-cli\src\commands\add-list.js:113:34)
    at Object.ArgParser.parse (C:\users\jason\node_modules\nomnom\nomnom.js:302:15)
    at Object.<anonymous> (C:\users\jason\node_modules\trello-cli\bin\trello:74:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

Let me know if you need more or if there is a specific thing I can test.

**Comment by ksk100** [comment]
Thanks for this.   Did you get any errors when doing the authentication, or
when saving the authentication token?
Am 16.04.2016 21:08 schrieb "durmiun" <notifications@github.com>:

**Comment by durmiun** [comment]
No errors during authentication or token generation.  I've set system-level environment variables for the trello auth and trello token values (per the instructions):

TRELLO_DEVELOPER_PUBLIC_KEY=<api key>
TRELLO_MEMBER_TOKEN=<token value>

**Comment by ksk100** [comment]
Which instructions are those?

I think what you might need to do is go here https://trello.com/app-key to get a developer key, and then put that in your `~/.trello-cli/config.json` file.

**Comment by durmiun** [comment]
Sweet mother of god... Please scratch this for now.  I've apparently installed and been following directions for 2 completely different Trello-CLI packages.  I can't confirm anything is correct until I completely remove both packages and then reinstall yours.

Just for confirmation, I have a config.json.dist file in my trello-cli folder.  It has an entry where I can place my API key, so I'm assuming this is the right file.   Do I need to rename it to remove the ".dist" extension?

Sorry for the confusion here.  This should be chalked up to "user error" for the time being -_-

**Comment by ksk100** [comment]
Yes remove the '.dist'

2016-04-18 19:16 GMT+01:00 durmiun <notifications@github.com>:
