### ISSUE TITLE
First run fails

### ISSUE THREAD

**Issue by hughwilliams94** [mheap/trello-cli#37]
After `npm install` the first run of `trello` fails with this message:

```
/usr/lib/node_modules/trello-cli/src/authenticate.js:53
            throw e;
            ^

TypeError: path must be a string or Buffer
    at Object.fs.mkdirSync (fs.js:855:18)
    at Auth.writeAuthFile (/usr/lib/node_modules/trello-cli/src/authenticate.js:49:17)
    at Auth.loadAuthCache (/usr/lib/node_modules/trello-cli/src/authenticate.js:22:14)
    at Auth.getToken (/usr/lib/node_modules/trello-cli/src/authenticate.js:40:33)
    at __ (/usr/lib/node_modules/trello-cli/src/node-trello-wrapper.js:7:69)
    at Object.<anonymous> (/usr/lib/node_modules/trello-cli/bin/trello:38:51)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

```

This happens with both a global or local `npm install`. Running on a GalliumOS, a version of Ubuntu 16.04 modified for Chromebooks. No configuration file is produced.

**Comment by mheap** [comment]
Thanks for the report @hughwilliams94. That should be fixed now
